name: Auto Fresh Cache
on:
  push:
    branches: [ master ]
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://purge.jsdelivr.net/gh/shui/CustomList@latest/custom.txt
