name: CI
on:
  commit_comment:
    branches: [ master ]

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://purge.jsdelivr.net/gh/shui/CustomList@latest/custom.txt
